# Generated by Django 4.2.30 on 2026-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='insights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
